version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: l1p3
      POSTGRES_USER: postgres
      POSTGRES_DB: api-rest-produtos
    ports:
      - 5432:5432
    volumes:
      - restpsql:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:3002

volumes:
  restpsql:
    external: true

